-- Delete all existing data from 'volunteer' and 'ben' tables
DELETE FROM volunteer;
DELETE FROM ben;


-- Inserindo 5 registros na tabela 'ben'
INSERT INTO ben (address, age, descriptions, email, firstName, lastName, phone, services)
VALUES
    ('Avenue Elias Garcia, 150', 69, 'Good afternoon, I need help finding transportation to my appointment tomorrow. I can''t drive and my son is unavailable to take me to the hospital. If anyone could be a dear i would really appreciate it.', 'conceicao55@sapo.pt', 'Maria', 'da Conceição', '910110101', 'Transport'),
    ('Martim Moniz Square, 12', 70, 'Hello, I have difficulty cooking my daily meals. I need someone to teach me how to make simple and quick meals. I know the basics, but I can’t make dishes like I used to. Can someone help me with easy recipes?', 'jaquim@sapo.pt', 'Manuel', 'Joaquim', '935551337', 'Cooking'),
    ('Dom Carlos I Avenue, 45', 79, 'Good morning, does anyone know how I can fix a small problem with the plumbing at home? The kitchen tap is leaking, and I’ve tried tightening it, but I can’t fix it. If anyone knows a good professional or can help, I would be very grateful.', 'oamigoze@gmail.com', 'António', 'José', '964042001', 'Maintenance'),
    ('Luísa Todi Avenue, 60', 67, 'Hello, I need help doing my shopping. I can no longer carry heavy bags due to my illness, and moving around the supermarket is difficult. If anyone can accompany me or even do the shopping for me, I would really appreciate it.', 'margarida_56@hotmail.com', 'Ana', 'Margarida', '915551234', 'Shopping help'),
    ('Republic Square, 25', 83, 'Good afternoon, I’ve been feeling quite tired and can no longer take care of myself the way I used to. I need someone to help me with some things, like preparing a meal or simply making me a bit of company. If anyone can help, I would gladly appreciated it.', 'joao.deus@gmail.com', 'João', 'de Deus', '928050000', 'Caring'),
    ('Sun Street, 18', 74, 'Good mourning, I need help with painting a wall in my living room that has started to grow some ugly mold. The paint is also peeling off, and I’m unable to do it myself due to my age. I would really appreciate if someone could assist.', 'jose.martins@gmail.com', 'José', 'Martins', '935476821', 'Maintenance'),
    ('Liberty Garden, 10', 75, 'Good afternoon, I need help arranging a ride to the doctor tomorrow. I’m unable to drive myself and my family is busy. If someone could kindly assist, I’d be truly grateful.', 'helena_costa@sapo.pt', 'Helena', 'Costa', '917111222', 'Transport'),
    ('Cans Street, 50', 68, 'Hello, I’m having trouble cooking meals that are both nutritious and simple. I used to cook a lot, but now I’m finding it difficult. Can anyone share some easy and healthy recipes with me?', 'ricardo.santos@mail.com', 'Ricardo', 'Santos', '936789456', 'Cooking'),
    ('Saint Teresa Street, 33', 80, 'Good morning, my faucet is leaking, and I’ve tried fixing it myself but without success. Does anyone know a plumber or have tips to stop the leak? Your help would be greatly appreciated!', 'sergio_ribeiro@gmail.com', 'Sérgio', 'Ribeiro', '963222789', 'Maintenance'),
    ('Peace Avenue, 22', 72, 'Hello, I need some help with my shopping. It’s becoming too much for me to carry, and I can’t walk long distances. If someone could assist me in getting groceries, I’d be very thankful.', 'sofia.silva@hotmail.com', 'Sofia', 'Silva', '915234567', 'Shopping help'),
    ('Liberty Street, 15', 84, 'Good afternoon, I’m feeling very weak lately and can’t take care of myself like I used to. I need some assistance with daily tasks, like cooking or simply chatting. Anyone willing to help would be a blessing.', 'maria.joana@gmail.com', 'Maria', 'Joana', '923456789', 'Caring');


INSERT INTO volunteer (address, age, descriptions, email, firstName, lastName, phone, services)
VALUES
    ('Three Castles Street, 155', 29, 'Good afternoon! My name is João. I know it’s not always easy to get around or take care of things at home, so I’d like to help! I can drive you to your appointments or help with small repairs around the house. I’ve got a bit of experience with fixing things, and I’m always happy to lend a hand. If you need anything, please don’t hesitate to reach out. I’m just a text', 'joaosilva@gmail.com', 'João', 'Ferreira', '915672834', 'Transport Maintenance'),
    ('Conceição Street, 18', 32, 'Hello, my name is Rita, and I’m here to help with cooking or just keeping you company! I know how hard it can be to cook every day, especially when the recipes are complicated. I’d love to teach you some simple, tasty dishes that are easy to make. If you need someone to chat with while you cook, or even if you just want someone around, I’d be happy to visit and spend time together. :)', 'santinha@hotmail.com' 'Mariana', 'Santos', '936480256', 'Cooking Caring'),
    ('Roma Avenue, 50', 40, 'Hello, I’m Sofia, and I understand how difficult it can be to carry heavy bags or go out shopping when you’re not feeling your best. I can help with shopping or even cook a few simple meals for you. I also enjoy spending time together, so if you need someone to chat with while we’re out or while I prepare something for you, I’d be more than happy to help.', 'renata.martins@hotmail.com', 'Renata', 'Martins', '924731509', 'Shopping Help Caring'),
    ('Operários Street, 65 ', 38, 'Hello, I’m Miguel, and I can help with cleaning or organizing around the house! It can be overwhelming to keep up with things sometimes, so if you need someone to help tidy up or even just sort out a few things, I’d be more than happy to assist. Let me know what I can do to make your home feel more comfortable!', 'miguel.oliveira@gmail.com', 'Miguel', 'Oliveira', '917254683', 'Maintenance Caring'),
    ('João Crisóstomo Avenue, 30', 33, 'Good afternoon, my name’s Paula, and I’m here to help with transportation. If you need a lift to the doctor’s office or the store, I can take you =). I know how difficult it can be to get around sometimes, so I want to make it easier for you. I also love spending time with people, so if you’d like some company on your trip, I’ll gladly chat with you along the way!', 'paula.gomes@iol.com', 'Paula', 'Gomes', '923148675', 'Transport Caring'),
    ('Sun Street, 95', 30, 'Good morning, my name is Catarina, and I’m here to help with anything around the house. If you need help with light cleaning, organizing, or even taking out the trash, I’m more than happy to lend a hand! I also enjoy helping with gardening, so if you’d like to freshen up your yard or balcony, feel free to ask. I’m always just a phone call away.', 'catcostas@gmail.com', 'Catarina', 'Costa', '920335189', 'Maintenance Caring'),
    ('Liberty Garden, 60', 29, 'Hi, I’m Jorge, and I’m happy to help with any transportation needs you have. Whether you need a ride to appointments or just a quick trip to the store, I’m available to take you! I also enjoy keeping people company during the ride, so we can chat if you like. Let me know if you need help getting around.', 'jorge.martins@live.com', 'Jorge', 'Martins', '919741263', 'Transport Caring'),
    ('Cans Street, 120', 40, 'Hello, my name is Ana, and I’m here to assist with meal preparation or even just keeping you company. I love to cook and would be happy to teach you some simple, healthy recipes, or even cook for you. If you just want to chat or need help with grocery shopping, I can do that as well. I’m here to make things easier for you!', 'ana.alves@hotmail.com', 'Ana', 'Alves', '923876410', 'Cooking Shopping Help Caring'),
    ('Saint Teresa Street, 105', 36, 'Good afternoon, I’m Rui, and I can help with light maintenance tasks around the house. If you need assistance with repairs like fixing a door or painting a room, I can take care of it! I also enjoy organizing spaces and would be happy to help tidy up or sort through things you no longer need. Just let me know how I can assist!', 'rui.santos@yahoo.com', 'Rui', 'Santos', '931592804', 'Maintenance Caring'),
    ('Peace Street, 70', 31, 'Hello, I’m Mariana, and I’d love to help with shopping or running errands for you. If you need help picking up groceries, medications, or anything else, I’m happy to assist! I’m also available to help you with light cleaning or organizing at home. If you’re feeling down or need someone to chat with, I’d be glad to spend some time with you.', 'mariana.pereira@hotmail.com', 'Mariana', 'Pereira', '924351736', 'Shopping Help Maintenance Caring');




